# permissions for end users to view ekimonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ekimonitor-viewer-role
rules:
- apiGroups:
  - iaaseki.cmss
  resources:
  - ekimonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iaaseki.cmss
  resources:
  - ekimonitors/status
  verbs:
  - get
