# permissions for end users to edit ekimonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ekimonitor-editor-role
rules:
- apiGroups:
  - iaaseki.cmss
  resources:
  - ekimonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iaaseki.cmss
  resources:
  - ekimonitors/status
  verbs:
  - get
